export const LINES_UPDATED = "LINES_UPDATED";
export const LINES_NAME_OBS_LOADED = "LINES_NAME_OBS_LOADED";
export const LINE_LOADED = "LINE_LOADED";
export const DEPARTURES_LOADED = "DEPARTURES_LOADED";
