export const LINES_UPDATED = "LINES_UPDATED";
export const LINES_NAME_OBS_LOADED = "LINES_NAME_OBS_LOADED";
export const LINE_LOADED = "LINE_LOADED";
export const DEPARTURES_LOADED = "DEPARTURES_LOADED";
export const LINES_BY_DEPARTURE_LOADED = "LINES_BY_DEPARTURE_LOADED";
export const USER_DATA_LOADED = "USER_DATA_LOADED";
export const LAST_UPDATE_UPDATED = "LAST_UPDATE_UPDATED";
